import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import CssModulesPlugin from "esbuild-css-modules-plugin";
import fs from 'fs'

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [
		CssModulesPlugin({
			generateBuildId: (filePath, classNames, hash) => {
				return `affinity-plugin-${classNames}-${hash}`;
			},
			force: true,
		}),
		{
			name: 'rename-styles',
			setup(build) {
				build.onEnd(() => {
					const oldPath = 'main.css';
					const newPath = 'styles.css';

					if (fs.existsSync(oldPath)) {
						fs.renameSync(oldPath, newPath);
					}
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
